kibot:
  version: 1

global:
  variant: 'Default'

outputs:
  - name: 'position'
    comment: 'Generate surface-mount positions for PCBWay (CSV)'
    type: 'position'
    dir: 'Assembly'
    options:
      format: 'CSV'
      output: '%f%r-pos.%x'
      separate_files_for_front_and_back: false
      units: 'millimeters'
